version: "3.8"

services:
  panopticon:
    image: "ianburgwin/panopticon"
    volumes:
      - /opt/panopticon-logs:/home/panopticon/logs
    environment:
      PANOPTICON_TOKEN_FILE: /run/secrets/token
    secrets:
      - token
    restart: always

secrets:
  token:
    file: /opt/secrets/panopticon/token
